import datetime as _datetime
import os as _os
from collections.abc import Iterator as _Iterator, Sequence as _Sequence
from typing import Literal as _Literal, NoReturn as _Never, final as _final, overload as _overload

from . import shared as _shared
from .enum import table as _table
from .enum import text as _text

_Path = str | _os.PathLike[str]
_RevisionView = _Literal["accepted", "tracked"]
_BorderStyle = _Literal[
    "none", "single", "thick", "double", "dotted", "dashed", "dotDash", "wave"
]
_BorderEdge = _Literal["top", "bottom", "left", "right", "insideH", "insideV"]
_Margins = tuple[
    _shared.Length | None, _shared.Length | None, _shared.Length | None, _shared.Length | None
]
__all__ = [
    "Bookmark", "BoundingBox", "Cell", "CellCollection", "CellParagraphCollection",
    "Comment", "ComparisonDiagnostic", "ContentFragment", "CoreProperties", "Document", "Font",
    "HeaderFooterVariant", "Hyperlink", "LayoutBackedFieldUpdateReport", "LayoutFragment", "LayoutPage", "ListLevel", "Paragraph", "ParagraphCollection",
    "ParagraphFormat", "Revision", "Row", "RowCollection", "Run", "RunCollection", "RunPosition",
    "RunRange", "Section", "Story", "StoryItem", "StoryRunPosition", "StoryRunRange", "Style",
    "SvgDiagnostic", "SvgRenderResult", "Table", "TableCollection", "TocRebuildReport",
]


@_final
class RunPosition:
    def __new__(cls, *, body_index: int, run_index: int) -> RunPosition: ...
    @property
    def body_index(self) -> int: ...
    @property
    def run_index(self) -> int: ...


@_final
class RunRange:
    def __new__(cls, *, start: RunPosition, end: RunPosition) -> RunRange: ...
    @property
    def start(self) -> RunPosition: ...
    @property
    def end(self) -> RunPosition: ...


@_final
class Bookmark:
    """A bookmark, or a marker problem, read by ``Document.bookmarks``.

    ``range`` counts paragraphs through tables and block content controls.
    ``direct_range`` uses the direct body index ``add_bookmark`` takes and is
    ``None`` when a marker sits in a table cell or a block content control.
    """

    def __new__(
        cls,
        *,
        id: int | None,
        name: str | None,
        range: RunRange | None,
        direct_range: RunRange | None,
        text: str,
        issue: str | None,
    ) -> Bookmark: ...
    @property
    def id(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def range(self) -> RunRange | None: ...
    @property
    def direct_range(self) -> RunRange | None: ...
    @property
    def text(self) -> str: ...
    @property
    def issue(self) -> str | None: ...


@_final
class Comment:
    def __new__(
        cls,
        *,
        id: int,
        author: str | None,
        initials: str | None,
        date: str | None,
        text: str,
        parent_id: int | None,
        resolved: bool,
        anchor_text: str | None = None,
        anchor: StoryRunRange | None = None,
    ) -> Comment: ...
    @property
    def id(self) -> int: ...
    @property
    def author(self) -> str | None: ...
    @property
    def initials(self) -> str | None: ...
    @property
    def date(self) -> str | None: ...
    @property
    def text(self) -> str: ...
    @property
    def parent_id(self) -> int | None: ...
    @property
    def resolved(self) -> bool: ...
    @property
    def anchor_text(self) -> str | None: ...
    @property
    def anchor(self) -> StoryRunRange | None: ...


@_final
class ComparisonDiagnostic:
    def __new__(cls, *, location: str, message: str) -> ComparisonDiagnostic: ...
    @property
    def location(self) -> str: ...
    @property
    def message(self) -> str: ...


@_final
class SvgDiagnostic:
    def __new__(cls, *, path: str, message: str) -> SvgDiagnostic: ...
    @property
    def path(self) -> str: ...
    @property
    def message(self) -> str: ...


@_final
class SvgRenderResult:
    def __new__(
        cls, *, svg: str, diagnostics: _Sequence[SvgDiagnostic]
    ) -> SvgRenderResult: ...
    @property
    def svg(self) -> str: ...
    @property
    def diagnostics(self) -> tuple[SvgDiagnostic, ...]: ...


@_final
class BoundingBox:
    def __new__(
        cls, *, x: float, y: float, width: float, height: float
    ) -> BoundingBox: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...


@_final
class LayoutFragment:
    def __new__(
        cls,
        *,
        body_index: int,
        physical_page: int,
        displayed_page: int,
        bounds: BoundingBox,
    ) -> LayoutFragment: ...
    @property
    def body_index(self) -> int: ...
    @property
    def physical_page(self) -> int: ...
    @property
    def displayed_page(self) -> int: ...
    @property
    def bounds(self) -> BoundingBox: ...


@_final
class LayoutPage:
    def __new__(
        cls,
        *,
        page_number: int,
        displayed_page_number: int,
        width: float,
        height: float,
    ) -> LayoutPage: ...
    @property
    def page_number(self) -> int: ...
    @property
    def displayed_page_number(self) -> int: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...


@_final
class LayoutBackedFieldUpdateReport:
    def __new__(
        cls,
        *,
        page_fields: int,
        num_pages_fields: int,
        page_reference_fields: int,
        diagnostics: tuple[str, ...],
        section_fields: int = 0,
        section_pages_fields: int = 0,
    ) -> LayoutBackedFieldUpdateReport: ...
    @property
    def page_fields(self) -> int: ...
    @property
    def num_pages_fields(self) -> int: ...
    @property
    def page_reference_fields(self) -> int: ...
    @property
    def section_fields(self) -> int: ...
    @property
    def section_pages_fields(self) -> int: ...
    @property
    def updated_count(self) -> int: ...
    @property
    def diagnostics(self) -> tuple[str, ...]: ...
    @property
    def diagnostic_count(self) -> int: ...


@_final
class TocRebuildReport:
    def __new__(
        cls, *, entry_count: int, bookmark_count: int, diagnostics: tuple[str, ...]
    ) -> TocRebuildReport: ...
    @property
    def entry_count(self) -> int: ...
    @property
    def bookmark_count(self) -> int: ...
    @property
    def diagnostics(self) -> tuple[str, ...]: ...
    @property
    def diagnostic_count(self) -> int: ...


@_final
class Revision:
    def __new__(
        cls,
        *,
        id: int,
        author: str,
        timestamp: str | None,
        kind: str,
        story: Story | None = None,
    ) -> Revision: ...
    @property
    def id(self) -> int: ...
    @property
    def author(self) -> str: ...
    @property
    def timestamp(self) -> str | None: ...
    @property
    def kind(self) -> str: ...
    @property
    def story(self) -> Story | None: ...


@_final
class Story:
    def __new__(cls, *, kind: str, part_name: str, owner_index: int) -> Story: ...
    @property
    def kind(self) -> str: ...
    @property
    def part_name(self) -> str: ...
    @property
    def owner_index(self) -> int: ...


@_final
class StoryItem:
    def __new__(
        cls,
        *,
        story: Story,
        kind: str,
        index_path: tuple[int, ...],
        text: str | None,
        xml: bytes | None = None,
        direct_body_index: int | None = None,
        revision: int = 0,
    ) -> StoryItem: ...
    @property
    def story(self) -> Story: ...
    @property
    def kind(self) -> str: ...
    @property
    def index_path(self) -> tuple[int, ...]: ...
    @property
    def direct_body_index(self) -> int | None: ...
    @property
    def text(self) -> str | None: ...
    @property
    def xml(self) -> bytes: ...
    @property
    def revision(self) -> int: ...


@_final
class StoryRunPosition:
    @_overload
    def __new__(
        cls, *, item: StoryItem, run_index: int, paragraph: None = None
    ) -> StoryRunPosition: ...
    @_overload
    def __new__(
        cls, *, item: None = None, run_index: int, paragraph: Paragraph
    ) -> StoryRunPosition: ...
    @property
    def item(self) -> StoryItem: ...
    @property
    def run_index(self) -> int: ...


@_final
class StoryRunRange:
    def __new__(
        cls, *, start: StoryRunPosition, end: StoryRunPosition
    ) -> StoryRunRange: ...
    @property
    def start(self) -> StoryRunPosition: ...
    @property
    def end(self) -> StoryRunPosition: ...


@_final
class ContentFragment:
    def __new__(cls, *, _private: _Never) -> ContentFragment: ...
    @property
    def kind(
        self,
    ) -> _Literal["paragraph", "table", "content_control", "field", "drawing", "preserved_node"]: ...


@_final
class Hyperlink:
    def __new__(
        cls,
        *,
        story: Story,
        index_path: tuple[int, ...],
        text: str,
        url: str | None,
        anchor: str | None,
        relationship_id: str | None,
    ) -> Hyperlink: ...
    @property
    def story(self) -> Story: ...
    @property
    def index_path(self) -> tuple[int, ...]: ...
    @property
    def text(self) -> str: ...
    @property
    def url(self) -> str | None: ...
    @property
    def anchor(self) -> str | None: ...
    @property
    def relationship_id(self) -> str | None: ...


@_final
class HeaderFooterVariant:
    def __new__(
        cls,
        *,
        section_index: int,
        kind: str,
        variant: str,
        story: Story | None,
        source_section: int | None,
        inherited: bool,
    ) -> HeaderFooterVariant: ...
    @property
    def section_index(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def variant(self) -> str: ...
    @property
    def story(self) -> Story | None: ...
    @property
    def source_section(self) -> int | None: ...
    @property
    def inherited(self) -> bool: ...


@_final
class Section:
    def __new__(
        cls,
        *,
        ordinal: int,
        is_final: bool,
        orientation: str | None,
        page_width: int | None,
        page_height: int | None,
        margin_top: int | None,
        margin_right: int | None,
        margin_bottom: int | None,
        margin_left: int | None,
        gutter: int | None,
        column_count: int | None,
        column_spacing: int | None,
        page_number_start: int | None,
        header_distance: int | None,
        footer_distance: int | None,
        different_first_page: bool | None,
        break_type: str | None,
    ) -> Section: ...
    @property
    def ordinal(self) -> int: ...
    @property
    def is_final(self) -> bool: ...
    @property
    def orientation(self) -> str | None: ...
    @property
    def page_width(self) -> int | None: ...
    @property
    def page_height(self) -> int | None: ...
    @property
    def margin_top(self) -> int | None: ...
    @property
    def margin_right(self) -> int | None: ...
    @property
    def margin_bottom(self) -> int | None: ...
    @property
    def margin_left(self) -> int | None: ...
    @property
    def gutter(self) -> int | None: ...
    @property
    def column_count(self) -> int | None: ...
    @property
    def column_spacing(self) -> int | None: ...
    @property
    def page_number_start(self) -> int | None: ...
    @property
    def header_distance(self) -> int | None: ...
    @property
    def footer_distance(self) -> int | None: ...
    @property
    def different_first_page(self) -> bool | None: ...
    @property
    def break_type(self) -> str | None: ...


@_final
class Style:
    def __new__(
        cls,
        *,
        style_id: str,
        name: str | None,
        based_on: str | None,
        style_type: str,
        linked_style: str | None,
        next_style: str | None,
        priority: int | None,
        auto_redefine: bool | None,
        hidden: bool | None,
        semi_hidden: bool | None,
        unhide_when_used: bool | None,
        quick_format: bool | None,
        locked: bool | None,
        is_default: bool,
    ) -> Style: ...
    @property
    def style_id(self) -> str: ...
    @property
    def name(self) -> str | None: ...
    @property
    def based_on(self) -> str | None: ...
    @property
    def style_type(self) -> str: ...
    @property
    def linked_style(self) -> str | None: ...
    @property
    def next_style(self) -> str | None: ...
    @property
    def priority(self) -> int | None: ...
    @property
    def auto_redefine(self) -> bool | None: ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def semi_hidden(self) -> bool | None: ...
    @property
    def unhide_when_used(self) -> bool | None: ...
    @property
    def quick_format(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def is_default(self) -> bool: ...


@_final
class ListLevel:
    def __new__(
        cls,
        *,
        format: str = "decimal",
        text: str | None = None,
        start: int | None = None,
        left_indent: int | None = None,
        hanging_indent: int | None = None,
    ) -> ListLevel: ...
    @property
    def format(self) -> str: ...
    @property
    def text(self) -> str | None: ...
    @property
    def start(self) -> int | None: ...
    @property
    def left_indent(self) -> int | None: ...
    @property
    def hanging_indent(self) -> int | None: ...


@_final
class CoreProperties:
    def __new__(cls, *, _private: _Never) -> CoreProperties: ...
    @property
    def author(self) -> str: ...
    @author.setter
    def author(self, value: str | None) -> None: ...
    @property
    def category(self) -> str: ...
    @category.setter
    def category(self, value: str | None) -> None: ...
    @property
    def comments(self) -> str: ...
    @comments.setter
    def comments(self, value: str | None) -> None: ...
    @property
    def content_status(self) -> str: ...
    @content_status.setter
    def content_status(self, value: str | None) -> None: ...
    @property
    def created(self) -> _datetime.datetime | None: ...
    @created.setter
    def created(self, value: _datetime.datetime | None) -> None: ...
    @property
    def identifier(self) -> str: ...
    @identifier.setter
    def identifier(self, value: str | None) -> None: ...
    @property
    def keywords(self) -> str: ...
    @keywords.setter
    def keywords(self, value: str | None) -> None: ...
    @property
    def language(self) -> str: ...
    @language.setter
    def language(self, value: str | None) -> None: ...
    @property
    def last_modified_by(self) -> str: ...
    @last_modified_by.setter
    def last_modified_by(self, value: str | None) -> None: ...
    @property
    def last_printed(self) -> _datetime.datetime | None: ...
    @last_printed.setter
    def last_printed(self, value: _datetime.datetime | None) -> None: ...
    @property
    def modified(self) -> _datetime.datetime | None: ...
    @modified.setter
    def modified(self, value: _datetime.datetime | None) -> None: ...
    @property
    def revision(self) -> int: ...
    @revision.setter
    def revision(self, value: int | None) -> None: ...
    @property
    def subject(self) -> str: ...
    @subject.setter
    def subject(self, value: str | None) -> None: ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str | None) -> None: ...
    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, value: str | None) -> None: ...


@_final
class Document:
    def __new__(cls, path: _Path | None = None) -> Document: ...
    @staticmethod
    def open(path: _Path) -> Document: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Document: ...
    def save(self, path: _Path) -> None: ...
    def to_bytes(self) -> bytes: ...
    def image_data(self, relationship_id: str) -> bytes | None: ...
    def replace_image(self, relationship_id: str, data: bytes) -> None: ...
    def replace_image_for_story(
        self, story: Story, relationship_id: str, data: bytes
    ) -> None: ...
    def set_picture_size(self, relationship_id: str, width: int, height: int) -> int: ...
    def split_run(
        self, body_index: int | Paragraph, run_index: int, character_offset: int
    ) -> int: ...
    def to_pdf(
        self,
        *,
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
        revision_view: _RevisionView = "accepted",
    ) -> bytes:
        """Render the document to PDF bytes.

        ``fonts`` gives ``(family, font bytes)`` pairs and ``font_dir`` a
        directory whose ``.ttf``, ``.otf`` and ``.ttc`` files are named after
        their family. When both are given, the directory fonts follow the
        ``fonts`` pairs. Those fonts come before every other font source, as
        ``rdocx convert --font-dir`` does, and a family they do not provide
        resolves as without them. A missing ``font_dir`` raises
        ``FileNotFoundError`` and a file ``NotADirectoryError``. The PNG, image
        and SVG render methods, ``layout`` and ``layout_page`` take the same two
        arguments. ``to_pdfa_deterministic`` does not.
        """
    def to_pdfa_deterministic(
        self, profile: _Literal["pdfa-2b", "pdfa-3b"] = "pdfa-2b"
    ) -> bytes: ...
    def render_page_to_png(
        self,
        page_index: int,
        dpi: float = 150.0,
        *,
        revision_view: _RevisionView = "accepted",
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> bytes | None: ...
    def render_page_to_svg(
        self,
        page_index: int,
        *,
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> SvgRenderResult | None: ...
    def render_all_pages(
        self,
        dpi: float = 150.0,
        *,
        revision_view: _RevisionView = "accepted",
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> list[bytes]: ...
    def render_pages(
        self,
        *,
        dpi: float = 150.0,
        format: str = "png",
        quality: int = 90,
        transparent: bool = False,
        pages: list[int] | None = None,
        revision_view: _RevisionView = "accepted",
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> list[bytes] | bytes: ...
    def compare(
        self,
        edited: Document,
        author: str,
        timestamp: str,
        *,
        granularity: _Literal["run", "word", "character"] = "run",
        ignore_formatting: bool = False,
        ignore_whitespace: bool = False,
        ignore_fields: bool = False,
        ignore_comments: bool = False,
        ignored_stories: _Sequence[
            _Literal["body", "header", "footer", "comment", "text_box", "footnote", "endnote"]
        ] | None = None,
    ) -> tuple[ComparisonDiagnostic, ...]:
        """Record how ``edited`` differs from this document as tracked changes.

        ``granularity`` selects the unit of a text change. The default ``"run"``
        replaces a changed run whole, while ``"word"`` and ``"character"`` mark
        only the changed words or characters. ``ignored_stories`` takes
        ``Story.kind`` names. The ignore options and ``ignored_stories`` are
        left-biased: an ignored difference or story keeps this document's
        content. With ``ignore_comments=True`` the result keeps this document's
        comments and anchors, and the comments of ``edited`` are not carried
        over. An unknown option value raises ``RdocxError``.
        """
    @property
    def comments(self) -> tuple[Comment, ...]: ...
    @property
    def sections(self) -> tuple[Section, ...]: ...
    def update_section(
        self,
        index: int,
        *,
        orientation: _Literal["portrait", "landscape"] | None = None,
        page_width: int | None = None,
        page_height: int | None = None,
        margin_top: int | None = None,
        margin_right: int | None = None,
        margin_bottom: int | None = None,
        margin_left: int | None = None,
        gutter: int | None = None,
        column_count: int | None = None,
        column_spacing: int | None = None,
        page_number_start: int | None = None,
        header_distance: int | None = None,
        footer_distance: int | None = None,
        different_first_page: bool | None = None,
        break_type: _Literal[
            "nextPage", "continuous", "evenPage", "oddPage", "nextColumn"
        ] | None = None,
    ) -> Section: ...
    def insert_section(self, index: int) -> None: ...
    def remove_section(self, index: int) -> None: ...
    @property
    def styles(self) -> tuple[Style, ...]: ...
    def add_style(
        self,
        name: str,
        style_type: _Literal["paragraph", "character", "table"] = "paragraph",
        *,
        style_id: str | None = None,
        based_on: str | None = None,
        next_style: str | None = None,
        font_name: str | None = None,
        font_size: int | None = None,
        bold: bool | None = None,
        italic: bool | None = None,
        color: _shared.RGBColor | None = None,
        space_before: int | None = None,
        space_after: int | None = None,
        left_indent: int | None = None,
        right_indent: int | None = None,
        first_line_indent: int | None = None,
    ) -> Style:
        """Create a style as python-docx's `styles.add_style` does.

        Unless `style_id` is given, the ID keeps the ASCII letters, digits and
        hyphens of the name, as Word derives one, or is `a`, `a0` and so on
        when none is left.
        `based_on` and `next_style` take an ID or a name. Lengths and the font
        size are EMU. Raises `KeyError` when a base or next style names no
        style, and `ValueError` for a duplicate ID or name or any other
        invalid argument.
        """
    def set_style(
        self,
        style: str,
        *,
        based_on: str | None = None,
        next_style: str | None = None,
        font_name: str | None = None,
        font_size: int | None = None,
        bold: bool | None = None,
        italic: bool | None = None,
        color: _shared.RGBColor | None = None,
        space_before: int | None = None,
        space_after: int | None = None,
        left_indent: int | None = None,
        right_indent: int | None = None,
        first_line_indent: int | None = None,
    ) -> Style:
        """Update the supplied formatting on a style selected by ID or name.

        Unspecified properties keep their existing values. Lengths and font
        size are EMU. Invalid style references or graph changes leave the
        document unchanged.
        """
    def remove_style(self, style: str) -> bool: ...
    def set_default_style(self, style: str) -> None: ...
    def add_numbering_definition(self, levels: _Sequence[ListLevel]) -> int: ...
    def add_numbering_instance(self, definition_id: int) -> int: ...
    def link_style_to_numbering(self, style: str, num_id: int, level: int) -> None: ...
    @property
    def stories(self) -> tuple[Story, ...]: ...
    @property
    def story_items(self) -> tuple[StoryItem, ...]: ...
    @property
    def header_footer_variants(self) -> tuple[HeaderFooterVariant, ...]: ...
    def create_section_story(
        self,
        section_index: int,
        kind: _Literal["header", "footer"],
        variant: _Literal["default", "first", "even"],
    ) -> Story: ...
    def link_section_story(
        self,
        section_index: int,
        kind: _Literal["header", "footer"],
        variant: _Literal["default", "first", "even"],
        story: Story,
    ) -> Story: ...
    def unlink_section_story(
        self,
        section_index: int,
        kind: _Literal["header", "footer"],
        variant: _Literal["default", "first", "even"],
    ) -> Story: ...
    @property
    def hyperlinks(self) -> tuple[Hyperlink, ...]: ...
    @property
    def core_properties(self) -> CoreProperties: ...
    @property
    def update_fields_on_open(self) -> bool | None: ...
    @update_fields_on_open.setter
    def update_fields_on_open(self, value: bool | None) -> None: ...
    def add_comment(
        self,
        range: RunRange | StoryRunRange,
        *,
        author: str,
        text: str,
        initials: str | None = None,
        date: str | None = None,
    ) -> int: ...
    def add_comment_on_text(
        self,
        anchor: str,
        *,
        author: str,
        text: str,
        occurrence: int = 0,
        initials: str | None = None,
        date: str | None = None,
    ) -> int: ...
    def move_comment(self, id: int, range: StoryRunRange) -> None:
        """Move an existing root thread to a checked current story range."""
        ...
    def move_comment_to_text(self, id: int, anchor: str, *, occurrence: int = 0) -> None:
        """Move an existing root thread onto a literal main-story occurrence."""
        ...
    def reply_to(
        self, parent_id: int, *, author: str, text: str, date: str | None = None
    ) -> int: ...
    def resolve_comment(self, id: int, *, resolved: bool = True) -> bool: ...
    def remove_comment(self, id: int) -> bool: ...
    @property
    def bookmarks(self) -> tuple[Bookmark, ...]: ...
    def add_bookmark(self, name: str, range: RunRange) -> int: ...
    def layout(
        self,
        *,
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> tuple[LayoutFragment, ...]: ...
    def layout_page(
        self,
        page_index: int,
        *,
        fonts: _Sequence[tuple[str, bytes]] | None = None,
        font_dir: _Path | None = None,
    ) -> LayoutPage | None: ...
    def rebuild_toc(self) -> TocRebuildReport: ...
    def replace_text_at(
        self, item: StoryItem, old: str, new: str, *, expect: int | None = None
    ) -> int: ...
    def try_replace_text(
        self, placeholder: str, replacement: str, *, expect: int | None = None
    ) -> int: ...
    def replace_all(
        self, pairs: _Sequence[tuple[str, str] | tuple[str, str, int | None]]
    ) -> tuple[int, ...]: ...
    def replace_all_regex(self, patterns: list[tuple[str, str]]) -> int: ...
    @property
    def revisions(self) -> tuple[Revision, ...]: ...
    def accept_all(self) -> int: ...
    def reject_all(self) -> int: ...
    def accept_revisions_by_author(self, author: str) -> int: ...
    def reject_revisions_by_author(self, author: str) -> int: ...
    def accept_revisions_in_date_range(self, *, start: str, end: str) -> int: ...
    def reject_revisions_in_date_range(self, *, start: str, end: str) -> int: ...
    def accept_revision_id(self, id: int) -> int: ...
    def reject_revision_id(self, id: int) -> int: ...
    def update_fields(
        self,
        *,
        now: _datetime.datetime | None = None,
        file_name: str | None = None,
        file_path: str | None = None,
        merge_fields: dict[str, str] | None = None,
        included_text: dict[str, str] | None = None,
        merge_record_number: int | None = None,
        merge_sequence_number: int | None = None,
    ) -> int: ...
    def set_header(self, text: str) -> None: ...
    def set_footer(self, text: str) -> None: ...
    def set_story_text(self, item: StoryItem, text: str) -> None: ...
    def add_hyperlink_to_story(self, story: Story, text: str, url: str) -> None: ...
    def set_hyperlink_url(self, hyperlink: Hyperlink, url: str) -> None: ...
    def remove_hyperlink(self, hyperlink: Hyperlink) -> None: ...
    def add_picture(
        self,
        data: bytes,
        filename: str,
        width: int | None = None,
        height: int | None = None,
        *,
        after: StoryItem | None = None,
    ) -> StoryItem: ...
    def update_page_fields(self) -> int: ...
    def update_layout_backed_fields(self) -> LayoutBackedFieldUpdateReport: ...
    def insert_toc(self, index: int, max_level: int = 3) -> None: ...
    @property
    def paragraphs(self) -> ParagraphCollection: ...
    @property
    def tables(self) -> TableCollection: ...
    def add_paragraph(self, text: str) -> Paragraph: ...
    def add_table(self, rows: int, cols: int) -> Table: ...
    def remove_content(self, index: int) -> bool: ...
    @_overload
    def find_content_index(self, content: Paragraph | Table) -> int: ...
    @_overload
    def find_content_index(self, content: str) -> int: ...
    def find_content_indices(self, text: str) -> tuple[int, ...]: ...
    def insert_paragraph(self, index: int, text: str) -> Paragraph: ...
    def insert_table(self, index: int, rows: int, cols: int) -> Table: ...
    def pop_content(self, index: int | StoryItem) -> ContentFragment: ...
    def insert_content(
        self, destination: int | StoryItem | Story, fragment: ContentFragment
    ) -> None: ...
    def clone_content(self, source: Paragraph | Table, destination: int) -> None: ...
    def move_content(self, source: Paragraph | Table, destination: int) -> None: ...


@_final
class Paragraph:
    def __new__(cls, *, _private: _Never) -> Paragraph: ...
    def replace_text(
        self, old: str, new: str, *, expect: int | None = None
    ) -> int: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str | None) -> None: ...
    @property
    def runs(self) -> RunCollection: ...
    @property
    def alignment(self) -> _text.WD_ALIGN_PARAGRAPH | None: ...
    @alignment.setter
    def alignment(self, value: _text.WD_ALIGN_PARAGRAPH | None) -> None: ...
    def add_run(self, text: str) -> Run: ...
    def add_hyperlink(self, text: str, url: str) -> Run: ...
    @property
    def paragraph_format(self) -> ParagraphFormat: ...
    @property
    def style(self) -> str | None: ...
    @style.setter
    def style(self, value: str | None) -> None:
        """Assign a paragraph style by ID, or by name as python-docx does.

        The ID is tried first, then the exact name, then the name regardless of
        case. Raises `KeyError` when no style has that ID or name, and
        `ValueError` when only a character, table or numbering style does.
        `None` removes the paragraph style.
        """
    @property
    def numbering(self) -> tuple[int, int] | None: ...
    @numbering.setter
    def numbering(self, value: tuple[int, int] | None) -> None: ...


@_final
class ParagraphCollection:
    def __new__(cls, *, _private: _Never) -> ParagraphCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Paragraph: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Paragraph]: ...
    def __iter__(self) -> _Iterator[Paragraph]: ...


@_final
class Run:
    def __new__(cls, *, _private: _Never) -> Run: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    def remove(self) -> None: ...
    @property
    def font(self) -> Font: ...
    @property
    def style_id(self) -> str | None: ...
    @style_id.setter
    def style_id(self, value: str | None) -> None: ...
    def add_tab(self) -> None: ...
    def add_field(self, instruction: str, cached_result: str = "") -> None: ...


@_final
class RunCollection:
    def __new__(cls, *, _private: _Never) -> RunCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Run: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Run]: ...
    def __iter__(self) -> _Iterator[Run]: ...


@_final
class Font:
    def __new__(cls, *, _private: _Never) -> Font: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str | None) -> None: ...
    @property
    def size(self) -> _shared.Length | None: ...
    @size.setter
    def size(self, value: int | None) -> None: ...
    @property
    def color(self) -> _shared.RGBColor | None: ...
    @color.setter
    def color(self, value: _shared.RGBColor | None) -> None: ...
    @property
    def bold(self) -> bool | None: ...
    @bold.setter
    def bold(self, value: bool | None) -> None: ...
    @property
    def italic(self) -> bool | None: ...
    @italic.setter
    def italic(self, value: bool | None) -> None: ...
    @property
    def underline(self) -> bool | _text.WD_UNDERLINE | None: ...
    @underline.setter
    def underline(self, value: bool | _text.WD_UNDERLINE | None) -> None: ...
    @property
    def strike(self) -> bool | None: ...
    @strike.setter
    def strike(self, value: bool | None) -> None: ...
    @property
    def highlight(self) -> _Literal[
        "black", "blue", "cyan", "darkBlue", "darkCyan", "darkGray", "darkGreen",
        "darkMagenta", "darkRed", "darkYellow", "green", "lightGray", "magenta",
        "none", "red", "white", "yellow",
    ] | None: ...
    @highlight.setter
    def highlight(self, value: _Literal[
        "black", "blue", "cyan", "darkBlue", "darkCyan", "darkGray", "darkGreen",
        "darkMagenta", "darkRed", "darkYellow", "green", "lightGray", "magenta",
        "none", "red", "white", "yellow",
    ] | None) -> None: ...
    @property
    def shading(self) -> str | None: ...
    @shading.setter
    def shading(self, value: str | None) -> None: ...


@_final
class ParagraphFormat:
    def __new__(cls, *, _private: _Never) -> ParagraphFormat: ...
    @property
    def alignment(self) -> _text.WD_ALIGN_PARAGRAPH | None: ...
    @alignment.setter
    def alignment(self, value: _text.WD_ALIGN_PARAGRAPH | None) -> None: ...
    @property
    def space_before(self) -> _shared.Length | None: ...
    @space_before.setter
    def space_before(self, value: int | None) -> None: ...
    @property
    def space_after(self) -> _shared.Length | None: ...
    @space_after.setter
    def space_after(self, value: int | None) -> None: ...
    @property
    def left_indent(self) -> _shared.Length | None: ...
    @left_indent.setter
    def left_indent(self, value: int | None) -> None: ...
    @property
    def right_indent(self) -> _shared.Length | None: ...
    @right_indent.setter
    def right_indent(self, value: int | None) -> None: ...
    @property
    def first_line_indent(self) -> _shared.Length | None: ...
    @first_line_indent.setter
    def first_line_indent(self, value: int | None) -> None: ...
    @property
    def line_spacing(self) -> _shared.Length | float | None: ...
    @line_spacing.setter
    def line_spacing(self, value: int | float | None) -> None: ...
    @property
    def keep_with_next(self) -> bool | None: ...
    @keep_with_next.setter
    def keep_with_next(self, value: bool | None) -> None: ...
    @property
    def keep_together(self) -> bool | None: ...
    @keep_together.setter
    def keep_together(self, value: bool | None) -> None: ...
    @property
    def page_break_before(self) -> bool | None: ...
    @page_break_before.setter
    def page_break_before(self, value: bool | None) -> None: ...
    @property
    def widow_control(self) -> bool | None: ...
    @widow_control.setter
    def widow_control(self, value: bool | None) -> None: ...


@_final
class Table:
    def __new__(cls, *, _private: _Never) -> Table: ...
    @property
    def rows(self) -> RowCollection: ...
    def cell(self, row: int, col: int) -> Cell: ...
    @property
    def style(self) -> str | None: ...
    @style.setter
    def style(self, value: str) -> None: ...
    @property
    def alignment(self) -> _table.WD_TABLE_ALIGNMENT | None: ...
    @alignment.setter
    def alignment(self, value: _table.WD_TABLE_ALIGNMENT) -> None: ...
    @property
    def width(self) -> _shared.Length | None: ...
    @width.setter
    def width(self, value: int) -> None: ...
    def set_borders(self, style: _BorderStyle, *, size: int, color: str) -> None: ...
    def set_border(
        self, edge: _BorderEdge, style: _BorderStyle, *, size: int, color: str
    ) -> None: ...
    def border(self, edge: _BorderEdge) -> tuple[str, int | None, str | None] | None: ...
    @property
    def cell_margins(self) -> _Margins | None: ...
    def set_cell_margins(self, *, top: int, right: int, bottom: int, left: int) -> None: ...
    @property
    def grid_widths(self) -> tuple[_shared.Length, ...]: ...
    @grid_widths.setter
    def grid_widths(self, value: _Sequence[int]) -> None: ...
    def set_column_width(self, column: int, width: int) -> None: ...
    def set_cell_grid_span(self, row: int, col: int, span: int | None) -> None: ...
    def set_cell_vertical_merge(
        self, row: int, col: int, merge: _Literal["restart", "continue"] | None
    ) -> None: ...
    def clone_row(self, index: int, at: int | None = None) -> Row: ...
    def remove_row(self, index: int) -> None: ...


@_final
class TableCollection:
    def __new__(cls, *, _private: _Never) -> TableCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Table: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Table]: ...
    def __iter__(self) -> _Iterator[Table]: ...


@_final
class Row:
    def __new__(cls, *, _private: _Never) -> Row: ...
    @property
    def cells(self) -> CellCollection: ...
    # height and height_rule read None for a w:trHeight with an auto rule,
    # which python-docx reads as its value and AUTO, or with no value.
    # Assigning a height keeps the rule of an exact height and writes a
    # minimum otherwise, so an auto rule, or an exact rule without a value,
    # becomes a minimum.
    @property
    def height(self) -> _shared.Length | None: ...
    @height.setter
    def height(self, value: int) -> None: ...
    @property
    def height_rule(self) -> _table.WD_ROW_HEIGHT_RULE | None: ...
    @height_rule.setter
    def height_rule(self, value: _table.WD_ROW_HEIGHT_RULE) -> None: ...
    @property
    def cant_split(self) -> bool | None: ...
    @cant_split.setter
    def cant_split(self, value: bool | None) -> None: ...
    @property
    def is_header(self) -> bool | None: ...
    @is_header.setter
    def is_header(self, value: bool | None) -> None: ...


@_final
class RowCollection:
    def __new__(cls, *, _private: _Never) -> RowCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Row: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Row]: ...
    def __iter__(self) -> _Iterator[Row]: ...


@_final
class Cell:
    def __new__(cls, *, _private: _Never) -> Cell: ...
    def replace_text(
        self, old: str, new: str, *, expect: int | None = None
    ) -> int: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def paragraphs(self) -> CellParagraphCollection: ...
    def add_paragraph(self, text: str) -> Paragraph: ...
    @property
    def width(self) -> _shared.Length | None: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def vertical_alignment(self) -> _table.WD_CELL_VERTICAL_ALIGNMENT | None: ...
    @vertical_alignment.setter
    def vertical_alignment(self, value: _table.WD_CELL_VERTICAL_ALIGNMENT) -> None: ...
    @property
    def grid_span(self) -> int: ...
    @property
    def vertical_merge(self) -> _Literal["restart", "continue"] | None: ...
    @property
    def shading(self) -> str | None: ...
    @shading.setter
    def shading(self, value: str) -> None: ...
    def border(self, edge: _BorderEdge) -> tuple[str, int | None, str | None] | None: ...
    def set_border(
        self, edge: _BorderEdge, style: _BorderStyle, *, size: int, color: str
    ) -> None: ...
    @property
    def margins(self) -> _Margins | None: ...
    def set_margins(self, *, top: int, right: int, bottom: int, left: int) -> None: ...


@_final
class CellCollection:
    def __new__(cls, *, _private: _Never) -> CellCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Cell: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Cell]: ...
    def __iter__(self) -> _Iterator[Cell]: ...


@_final
class CellParagraphCollection:
    def __new__(cls, *, _private: _Never) -> CellParagraphCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Paragraph: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Paragraph]: ...
    def __iter__(self) -> _Iterator[Paragraph]: ...
