import datetime as _datetime
import os as _os
from collections.abc import Iterator as _Iterator
from typing import NoReturn as _Never, final as _final, overload as _overload

from . import shared as _shared
from .enum import table as _table
from .enum import text as _text

_Path = str | _os.PathLike[str]
__all__ = [
    "BoundingBox", "Cell", "CellCollection", "CellParagraphCollection",
    "Comment", "ComparisonDiagnostic", "Document", "Font", "HeaderFooterVariant",
    "Hyperlink", "LayoutFragment", "LayoutPage", "Paragraph", "ParagraphCollection",
    "ParagraphFormat", "Revision", "Row", "RowCollection", "Run", "RunCollection", "RunPosition",
    "RunRange", "Section", "Story", "StoryItem", "Style", "Table", "TableCollection",
    "TocRebuildReport",
]


@_final
class RunPosition:
    def __new__(cls, *, body_index: int, run_index: int) -> RunPosition: ...
    @property
    def body_index(self) -> int: ...
    @property
    def run_index(self) -> int: ...


@_final
class RunRange:
    def __new__(cls, *, start: RunPosition, end: RunPosition) -> RunRange: ...
    @property
    def start(self) -> RunPosition: ...
    @property
    def end(self) -> RunPosition: ...


@_final
class Comment:
    def __new__(
        cls,
        *,
        id: int,
        author: str | None,
        initials: str | None,
        date: str | None,
        text: str,
        parent_id: int | None,
        resolved: bool,
    ) -> Comment: ...
    @property
    def id(self) -> int: ...
    @property
    def author(self) -> str | None: ...
    @property
    def initials(self) -> str | None: ...
    @property
    def date(self) -> str | None: ...
    @property
    def text(self) -> str: ...
    @property
    def parent_id(self) -> int | None: ...
    @property
    def resolved(self) -> bool: ...


@_final
class ComparisonDiagnostic:
    def __new__(cls, *, location: str, message: str) -> ComparisonDiagnostic: ...
    @property
    def location(self) -> str: ...
    @property
    def message(self) -> str: ...


@_final
class BoundingBox:
    def __new__(
        cls, *, x: float, y: float, width: float, height: float
    ) -> BoundingBox: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...


@_final
class LayoutFragment:
    def __new__(
        cls,
        *,
        body_index: int,
        physical_page: int,
        displayed_page: int,
        bounds: BoundingBox,
    ) -> LayoutFragment: ...
    @property
    def body_index(self) -> int: ...
    @property
    def physical_page(self) -> int: ...
    @property
    def displayed_page(self) -> int: ...
    @property
    def bounds(self) -> BoundingBox: ...


@_final
class LayoutPage:
    def __new__(
        cls,
        *,
        page_number: int,
        displayed_page_number: int,
        width: float,
        height: float,
    ) -> LayoutPage: ...
    @property
    def page_number(self) -> int: ...
    @property
    def displayed_page_number(self) -> int: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...


@_final
class TocRebuildReport:
    def __new__(
        cls, *, entry_count: int, bookmark_count: int, diagnostic_count: int
    ) -> TocRebuildReport: ...
    @property
    def entry_count(self) -> int: ...
    @property
    def bookmark_count(self) -> int: ...
    @property
    def diagnostic_count(self) -> int: ...


@_final
class Revision:
    def __new__(
        cls, *, id: int, author: str, timestamp: str | None, kind: str
    ) -> Revision: ...
    @property
    def id(self) -> int: ...
    @property
    def author(self) -> str: ...
    @property
    def timestamp(self) -> str | None: ...
    @property
    def kind(self) -> str: ...


@_final
class Story:
    def __new__(cls, *, kind: str, part_name: str, owner_index: int) -> Story: ...
    @property
    def kind(self) -> str: ...
    @property
    def part_name(self) -> str: ...
    @property
    def owner_index(self) -> int: ...


@_final
class StoryItem:
    def __new__(
        cls,
        *,
        story: Story,
        kind: str,
        index_path: tuple[int, ...],
        text: str | None,
    ) -> StoryItem: ...
    @property
    def story(self) -> Story: ...
    @property
    def kind(self) -> str: ...
    @property
    def index_path(self) -> tuple[int, ...]: ...
    @property
    def text(self) -> str | None: ...


@_final
class Hyperlink:
    def __new__(
        cls,
        *,
        story: Story,
        index_path: tuple[int, ...],
        text: str,
        url: str | None,
        anchor: str | None,
        relationship_id: str | None,
    ) -> Hyperlink: ...
    @property
    def story(self) -> Story: ...
    @property
    def index_path(self) -> tuple[int, ...]: ...
    @property
    def text(self) -> str: ...
    @property
    def url(self) -> str | None: ...
    @property
    def anchor(self) -> str | None: ...
    @property
    def relationship_id(self) -> str | None: ...


@_final
class HeaderFooterVariant:
    def __new__(
        cls,
        *,
        section_index: int,
        kind: str,
        variant: str,
        story: Story | None,
        source_section: int | None,
        inherited: bool,
    ) -> HeaderFooterVariant: ...
    @property
    def section_index(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def variant(self) -> str: ...
    @property
    def story(self) -> Story | None: ...
    @property
    def source_section(self) -> int | None: ...
    @property
    def inherited(self) -> bool: ...


@_final
class Section:
    def __new__(
        cls,
        *,
        ordinal: int,
        is_final: bool,
        orientation: str | None,
        page_width: int | None,
        page_height: int | None,
        margin_top: int | None,
        margin_right: int | None,
        margin_bottom: int | None,
        margin_left: int | None,
        gutter: int | None,
        column_count: int | None,
        column_spacing: int | None,
        page_number_start: int | None,
        header_distance: int | None,
        footer_distance: int | None,
        different_first_page: bool | None,
        break_type: str | None,
    ) -> Section: ...
    @property
    def ordinal(self) -> int: ...
    @property
    def is_final(self) -> bool: ...
    @property
    def orientation(self) -> str | None: ...
    @property
    def page_width(self) -> int | None: ...
    @property
    def page_height(self) -> int | None: ...
    @property
    def margin_top(self) -> int | None: ...
    @property
    def margin_right(self) -> int | None: ...
    @property
    def margin_bottom(self) -> int | None: ...
    @property
    def margin_left(self) -> int | None: ...
    @property
    def gutter(self) -> int | None: ...
    @property
    def column_count(self) -> int | None: ...
    @property
    def column_spacing(self) -> int | None: ...
    @property
    def page_number_start(self) -> int | None: ...
    @property
    def header_distance(self) -> int | None: ...
    @property
    def footer_distance(self) -> int | None: ...
    @property
    def different_first_page(self) -> bool | None: ...
    @property
    def break_type(self) -> str | None: ...


@_final
class Style:
    def __new__(
        cls,
        *,
        style_id: str,
        name: str | None,
        based_on: str | None,
        style_type: str,
        linked_style: str | None,
        next_style: str | None,
        priority: int | None,
        auto_redefine: bool | None,
        hidden: bool | None,
        semi_hidden: bool | None,
        unhide_when_used: bool | None,
        quick_format: bool | None,
        locked: bool | None,
        is_default: bool,
    ) -> Style: ...
    @property
    def style_id(self) -> str: ...
    @property
    def name(self) -> str | None: ...
    @property
    def based_on(self) -> str | None: ...
    @property
    def style_type(self) -> str: ...
    @property
    def linked_style(self) -> str | None: ...
    @property
    def next_style(self) -> str | None: ...
    @property
    def priority(self) -> int | None: ...
    @property
    def auto_redefine(self) -> bool | None: ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def semi_hidden(self) -> bool | None: ...
    @property
    def unhide_when_used(self) -> bool | None: ...
    @property
    def quick_format(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def is_default(self) -> bool: ...


@_final
class Document:
    def __new__(cls, path: _Path | None = None) -> Document: ...
    @staticmethod
    def open(path: _Path) -> Document: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Document: ...
    def save(self, path: _Path) -> None: ...
    def to_bytes(self) -> bytes: ...
    def to_pdf(self) -> bytes: ...
    def render_page_to_png(self, page_index: int, dpi: float = 150.0) -> bytes | None: ...
    def render_all_pages(self, dpi: float = 150.0) -> list[bytes]: ...
    def render_pages(
        self,
        *,
        dpi: float = 150.0,
        format: str = "png",
        quality: int = 90,
        transparent: bool = False,
        pages: list[int] | None = None,
    ) -> list[bytes] | bytes: ...
    def compare(
        self, edited: Document, author: str, timestamp: str
    ) -> tuple[ComparisonDiagnostic, ...]: ...
    @property
    def comments(self) -> tuple[Comment, ...]: ...
    @property
    def sections(self) -> tuple[Section, ...]: ...
    @property
    def styles(self) -> tuple[Style, ...]: ...
    @property
    def stories(self) -> tuple[Story, ...]: ...
    @property
    def story_items(self) -> tuple[StoryItem, ...]: ...
    @property
    def header_footer_variants(self) -> tuple[HeaderFooterVariant, ...]: ...
    @property
    def hyperlinks(self) -> tuple[Hyperlink, ...]: ...
    def add_comment(
        self,
        range: RunRange,
        *,
        author: str,
        text: str,
        initials: str | None = None,
    ) -> int: ...
    def reply_to(self, parent_id: int, *, author: str, text: str) -> int: ...
    def resolve_comment(self, id: int, *, resolved: bool = True) -> bool: ...
    def remove_comment(self, id: int) -> bool: ...
    def layout(self) -> tuple[LayoutFragment, ...]: ...
    def layout_page(self, page_index: int) -> LayoutPage | None: ...
    def rebuild_toc(self) -> TocRebuildReport: ...
    @property
    def revisions(self) -> tuple[Revision, ...]: ...
    def accept_all(self) -> int: ...
    def reject_all(self) -> int: ...
    def accept_revisions_by_author(self, author: str) -> int: ...
    def reject_revisions_by_author(self, author: str) -> int: ...
    def accept_revisions_in_date_range(self, *, start: str, end: str) -> int: ...
    def reject_revisions_in_date_range(self, *, start: str, end: str) -> int: ...
    def accept_revision_id(self, id: int) -> int: ...
    def reject_revision_id(self, id: int) -> int: ...
    def try_replace_text(self, placeholder: str, replacement: str) -> int: ...
    def replace_all_regex(self, patterns: list[tuple[str, str]]) -> int: ...
    def update_fields(
        self,
        *,
        now: _datetime.datetime | None = None,
        file_name: str | None = None,
        file_path: str | None = None,
        merge_fields: dict[str, str] | None = None,
        included_text: dict[str, str] | None = None,
        merge_record_number: int | None = None,
        merge_sequence_number: int | None = None,
    ) -> int: ...
    @property
    def paragraphs(self) -> ParagraphCollection: ...
    @property
    def tables(self) -> TableCollection: ...
    def add_paragraph(self, text: str) -> Paragraph: ...
    def add_table(self, rows: int, cols: int) -> Table: ...
    def remove_content(self, index: int) -> bool: ...


@_final
class Paragraph:
    def __new__(cls, *, _private: _Never) -> Paragraph: ...
    @property
    def text(self) -> str: ...
    @property
    def runs(self) -> RunCollection: ...
    @property
    def alignment(self) -> _text.WD_ALIGN_PARAGRAPH | None: ...
    @alignment.setter
    def alignment(self, value: _text.WD_ALIGN_PARAGRAPH | None) -> None: ...
    def add_run(self, text: str) -> Run: ...
    @property
    def paragraph_format(self) -> ParagraphFormat: ...


@_final
class ParagraphCollection:
    def __new__(cls, *, _private: _Never) -> ParagraphCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Paragraph: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Paragraph]: ...
    def __iter__(self) -> _Iterator[Paragraph]: ...


@_final
class Run:
    def __new__(cls, *, _private: _Never) -> Run: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def font(self) -> Font: ...


@_final
class RunCollection:
    def __new__(cls, *, _private: _Never) -> RunCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Run: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Run]: ...
    def __iter__(self) -> _Iterator[Run]: ...


@_final
class Font:
    def __new__(cls, *, _private: _Never) -> Font: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str | None) -> None: ...
    @property
    def size(self) -> _shared.Length | None: ...
    @size.setter
    def size(self, value: int | None) -> None: ...
    @property
    def color(self) -> _shared.RGBColor | None: ...
    @color.setter
    def color(self, value: _shared.RGBColor | None) -> None: ...
    @property
    def bold(self) -> bool | None: ...
    @bold.setter
    def bold(self, value: bool | None) -> None: ...
    @property
    def italic(self) -> bool | None: ...
    @italic.setter
    def italic(self, value: bool | None) -> None: ...
    @property
    def underline(self) -> bool | _text.WD_UNDERLINE | None: ...
    @underline.setter
    def underline(self, value: bool | _text.WD_UNDERLINE | None) -> None: ...
    @property
    def strike(self) -> bool | None: ...
    @strike.setter
    def strike(self, value: bool | None) -> None: ...


@_final
class ParagraphFormat:
    def __new__(cls, *, _private: _Never) -> ParagraphFormat: ...
    @property
    def alignment(self) -> _text.WD_ALIGN_PARAGRAPH | None: ...
    @alignment.setter
    def alignment(self, value: _text.WD_ALIGN_PARAGRAPH | None) -> None: ...
    @property
    def space_before(self) -> _shared.Length | None: ...
    @space_before.setter
    def space_before(self, value: int | None) -> None: ...
    @property
    def space_after(self) -> _shared.Length | None: ...
    @space_after.setter
    def space_after(self, value: int | None) -> None: ...
    @property
    def left_indent(self) -> _shared.Length | None: ...
    @left_indent.setter
    def left_indent(self, value: int | None) -> None: ...
    @property
    def right_indent(self) -> _shared.Length | None: ...
    @right_indent.setter
    def right_indent(self, value: int | None) -> None: ...
    @property
    def first_line_indent(self) -> _shared.Length | None: ...
    @first_line_indent.setter
    def first_line_indent(self, value: int | None) -> None: ...
    @property
    def line_spacing(self) -> _shared.Length | float | None: ...
    @line_spacing.setter
    def line_spacing(self, value: int | float | None) -> None: ...
    @property
    def keep_with_next(self) -> bool | None: ...
    @keep_with_next.setter
    def keep_with_next(self, value: bool | None) -> None: ...
    @property
    def keep_together(self) -> bool | None: ...
    @keep_together.setter
    def keep_together(self, value: bool | None) -> None: ...
    @property
    def page_break_before(self) -> bool | None: ...
    @page_break_before.setter
    def page_break_before(self, value: bool | None) -> None: ...
    @property
    def widow_control(self) -> bool | None: ...
    @widow_control.setter
    def widow_control(self, value: bool | None) -> None: ...


@_final
class Table:
    def __new__(cls, *, _private: _Never) -> Table: ...
    @property
    def rows(self) -> RowCollection: ...
    def cell(self, row: int, col: int) -> Cell: ...
    @property
    def style(self) -> str | None: ...
    @style.setter
    def style(self, value: str) -> None: ...
    @property
    def alignment(self) -> _table.WD_TABLE_ALIGNMENT | None: ...
    @alignment.setter
    def alignment(self, value: _table.WD_TABLE_ALIGNMENT) -> None: ...
    @property
    def width(self) -> _shared.Length | None: ...
    @width.setter
    def width(self, value: int) -> None: ...


@_final
class TableCollection:
    def __new__(cls, *, _private: _Never) -> TableCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Table: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Table]: ...
    def __iter__(self) -> _Iterator[Table]: ...


@_final
class Row:
    def __new__(cls, *, _private: _Never) -> Row: ...
    @property
    def cells(self) -> CellCollection: ...


@_final
class RowCollection:
    def __new__(cls, *, _private: _Never) -> RowCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Row: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Row]: ...
    def __iter__(self) -> _Iterator[Row]: ...


@_final
class Cell:
    def __new__(cls, *, _private: _Never) -> Cell: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def paragraphs(self) -> CellParagraphCollection: ...
    def add_paragraph(self, text: str) -> Paragraph: ...
    @property
    def width(self) -> _shared.Length | None: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def vertical_alignment(self) -> _table.WD_CELL_VERTICAL_ALIGNMENT | None: ...
    @vertical_alignment.setter
    def vertical_alignment(self, value: _table.WD_CELL_VERTICAL_ALIGNMENT) -> None: ...


@_final
class CellCollection:
    def __new__(cls, *, _private: _Never) -> CellCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Cell: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Cell]: ...
    def __iter__(self) -> _Iterator[Cell]: ...


@_final
class CellParagraphCollection:
    def __new__(cls, *, _private: _Never) -> CellParagraphCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Paragraph: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Paragraph]: ...
    def __iter__(self) -> _Iterator[Paragraph]: ...
