import os as _os
from collections.abc import Iterator as _Iterator
from typing import NoReturn as _Never, final as _final, overload as _overload

from .enum.shapes import MSO_SHAPE as _MSO_SHAPE
from .util import Length as _Length

_Path = str | _os.PathLike[str]
__all__ = [
    "Presentation", "CommentAuthor", "Comment", "CommentReply",
    "BoundingBox", "TextLineLayout", "TextFrameLayout",
    "SlideLayout", "SlideLayoutCollection", "Slide",
    "SlideCollection", "Shape", "ShapeCollection", "PlaceholderCollection",
    "TextFrame", "Paragraph", "ParagraphCollection", "Run", "RunCollection",
    "Font", "Table", "Column", "ColumnCollection", "Cell",
]


@_final
class CommentAuthor:
    def __new__(cls, *, _private: _Never) -> CommentAuthor: ...
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def initials(self) -> str | None: ...
    @property
    def user_id(self) -> str: ...
    @property
    def provider_id(self) -> str: ...


@_final
class CommentReply:
    def __new__(cls, *, _private: _Never) -> CommentReply: ...
    @property
    def id(self) -> str: ...
    @property
    def author_id(self) -> str: ...
    @property
    def status(self) -> str | None: ...
    @property
    def created(self) -> str: ...
    @property
    def text(self) -> str: ...


@_final
class Comment:
    def __new__(cls, *, _private: _Never) -> Comment: ...
    @property
    def id(self) -> str: ...
    @property
    def author_id(self) -> str: ...
    @property
    def status(self) -> str | None: ...
    @property
    def created(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def replies(self) -> tuple[CommentReply, ...]: ...


@_final
class BoundingBox:
    def __new__(cls, *, _private: _Never) -> BoundingBox: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...


@_final
class TextLineLayout:
    def __new__(cls, *, _private: _Never) -> TextLineLayout: ...
    @property
    def paragraph_index(self) -> int: ...
    @property
    def text(self) -> str: ...
    @property
    def bounds(self) -> BoundingBox: ...
    @property
    def baseline(self) -> float: ...
    @property
    def font_size(self) -> float: ...


@_final
class TextFrameLayout:
    def __new__(cls, *, _private: _Never) -> TextFrameLayout: ...
    @property
    def slide_index(self) -> int: ...
    @property
    def shape_id(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def autofit(self) -> str: ...
    @property
    def frame(self) -> BoundingBox: ...
    @property
    def usable(self) -> BoundingBox: ...
    @property
    def font_scale(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def overflow(self) -> bool: ...
    @property
    def lines(self) -> tuple[TextLineLayout, ...]: ...


@_final
class Presentation:
    def __new__(cls, path: _Path | None = None) -> Presentation: ...
    def save(self, path: _Path) -> None: ...
    def to_bytes(self) -> bytes: ...
    def to_pdf(self) -> bytes: ...
    def render_slide_to_png(self, slide_index: int, dpi: float = 150.0) -> bytes | None: ...
    def render_all_slides(self, dpi: float = 150.0) -> list[bytes]: ...
    def text_layout(self, *, width_factor: float = 1.0) -> tuple[TextFrameLayout, ...]: ...
    def to_notes_pdf(self) -> bytes: ...
    def render_all_notes(self, dpi: float = 150.0) -> list[bytes]: ...
    @property
    def comment_authors(self) -> tuple[CommentAuthor, ...]: ...
    def add_comment_author(
        self,
        *,
        id: str,
        name: str,
        user_id: str,
        provider_id: str,
        initials: str | None = None,
    ) -> None: ...
    @property
    def slide_layouts(self) -> SlideLayoutCollection: ...
    @property
    def slides(self) -> SlideCollection: ...


@_final
class SlideLayout:
    def __new__(cls, *, _private: _Never) -> SlideLayout: ...
    @property
    def name(self) -> str | None: ...


@_final
class SlideLayoutCollection:
    def __new__(cls, *, _private: _Never) -> SlideLayoutCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> SlideLayout: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[SlideLayout]: ...
    def __iter__(self) -> _Iterator[SlideLayout]: ...


@_final
class Slide:
    def __new__(cls, *, _private: _Never) -> Slide: ...
    @property
    def shapes(self) -> ShapeCollection: ...
    @property
    def placeholders(self) -> PlaceholderCollection: ...
    @property
    def notes_text(self) -> str | None: ...
    @notes_text.setter
    def notes_text(self, value: str) -> None: ...
    @property
    def comments(self) -> tuple[Comment, ...]: ...
    def add_comment(
        self, *, id: str, author_id: str, created: str, text: str
    ) -> None: ...
    def reply_to_comment(
        self,
        comment_id: str,
        *,
        id: str,
        author_id: str,
        created: str,
        text: str,
    ) -> None: ...
    def move_comment(self, from_: int, to: int) -> None: ...
    def move_reply(self, comment_id: str, from_: int, to: int) -> None: ...


@_final
class SlideCollection:
    def __new__(cls, *, _private: _Never) -> SlideCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Slide: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Slide]: ...
    def __iter__(self) -> _Iterator[Slide]: ...
    def add_slide(self, layout: SlideLayout) -> Slide: ...


@_final
class Shape:
    def __new__(cls, *, _private: _Never) -> Shape: ...
    @property
    def left(self) -> _Length | None: ...
    @property
    def top(self) -> _Length | None: ...
    @property
    def width(self) -> _Length | None: ...
    @property
    def height(self) -> _Length | None: ...
    @property
    def shape_id(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def shapes(self) -> ShapeCollection: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def has_text_frame(self) -> bool: ...
    @property
    def text_frame(self) -> TextFrame: ...
    @property
    def has_table(self) -> bool: ...
    @property
    def table(self) -> Table: ...


@_final
class ShapeCollection:
    def __new__(cls, *, _private: _Never) -> ShapeCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Shape: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Shape]: ...
    def __iter__(self) -> _Iterator[Shape]: ...
    @property
    def title(self) -> Shape | None: ...
    @property
    def placeholders(self) -> PlaceholderCollection: ...
    def add_textbox(self, left: int, top: int, width: int, height: int) -> Shape: ...
    def add_shape(
        self, shape_type: _MSO_SHAPE, left: int, top: int, width: int, height: int
    ) -> Shape: ...
    def add_table(
        self, rows: int, cols: int, left: int, top: int, width: int, height: int
    ) -> Shape: ...
    def add_picture(
        self,
        image_file: _Path,
        left: int,
        top: int,
        width: int | None = None,
        height: int | None = None,
    ) -> Shape: ...


@_final
class PlaceholderCollection:
    def __new__(cls, *, _private: _Never) -> PlaceholderCollection: ...
    def __getitem__(self, placeholder_idx: int, /) -> Shape: ...


@_final
class TextFrame:
    def __new__(cls, *, _private: _Never) -> TextFrame: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def paragraphs(self) -> ParagraphCollection: ...
    def add_paragraph(self) -> Paragraph: ...
    @property
    def autofit(self) -> str | None: ...


@_final
class Paragraph:
    def __new__(cls, *, _private: _Never) -> Paragraph: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def level(self) -> int: ...
    @level.setter
    def level(self, value: int) -> None: ...
    @property
    def font(self) -> Font: ...
    @property
    def runs(self) -> RunCollection: ...


@_final
class ParagraphCollection:
    def __new__(cls, *, _private: _Never) -> ParagraphCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Paragraph: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Paragraph]: ...
    def __iter__(self) -> _Iterator[Paragraph]: ...


@_final
class Run:
    def __new__(cls, *, _private: _Never) -> Run: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def font(self) -> Font: ...


@_final
class RunCollection:
    def __new__(cls, *, _private: _Never) -> RunCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Run: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Run]: ...
    def __iter__(self) -> _Iterator[Run]: ...


@_final
class Font:
    def __new__(cls, *, _private: _Never) -> Font: ...
    @property
    def name(self) -> str | None: ...
    @property
    def color(self) -> str | None: ...
    @property
    def bold(self) -> bool | None: ...
    @bold.setter
    def bold(self, value: bool | None) -> None: ...
    @property
    def size(self) -> _Length | None: ...
    @size.setter
    def size(self, value: int | None) -> None: ...


@_final
class Table:
    def __new__(cls, *, _private: _Never) -> Table: ...
    @property
    def columns(self) -> ColumnCollection: ...
    def cell(self, row: int, col: int) -> Cell: ...


@_final
class ColumnCollection:
    def __new__(cls, *, _private: _Never) -> ColumnCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Column: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Column]: ...
    def __iter__(self) -> _Iterator[Column]: ...


@_final
class Column:
    def __new__(cls, *, _private: _Never) -> Column: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...


@_final
class Cell:
    def __new__(cls, *, _private: _Never) -> Cell: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
