import os as _os
from collections.abc import Iterator as _Iterator
from typing import IO as _IO, NoReturn as _Never, final as _final, overload as _overload

from .dml.color import RGBColor as _RGBColor
from .enum.dml import MSO_FILL_TYPE as _MSO_FILL_TYPE
from .enum.shapes import (
    MSO_CONNECTOR_TYPE as _MSO_CONNECTOR_TYPE,
    MSO_SHAPE as _MSO_SHAPE,
    MSO_SHAPE_TYPE as _MSO_SHAPE_TYPE,
)
from .util import Length as _Length

_Path = str | _os.PathLike[str]
_ImageFile = _Path | bytes | _IO[bytes]
__all__ = [
    "Presentation", "CommentAuthor", "Comment", "CommentReply",
    "SlideLayout", "SlideLayoutCollection", "Slide", "Background",
    "SlideCollection", "Shape", "ShapeCollection", "PlaceholderCollection",
    "Image", "AdjustmentCollection", "FillFormat", "LineFormat", "ColorFormat",
    "TextFrame", "Paragraph", "ParagraphCollection", "Run", "RunCollection",
    "Font", "Table", "Column", "ColumnCollection", "Cell",
]


@_final
class CommentAuthor:
    def __new__(cls, *, _private: _Never) -> CommentAuthor: ...
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def initials(self) -> str | None: ...
    @property
    def user_id(self) -> str: ...
    @property
    def provider_id(self) -> str: ...


@_final
class CommentReply:
    def __new__(cls, *, _private: _Never) -> CommentReply: ...
    @property
    def id(self) -> str: ...
    @property
    def author_id(self) -> str: ...
    @property
    def status(self) -> str | None: ...
    @property
    def created(self) -> str: ...
    @property
    def text(self) -> str: ...


@_final
class Comment:
    def __new__(cls, *, _private: _Never) -> Comment: ...
    @property
    def id(self) -> str: ...
    @property
    def author_id(self) -> str: ...
    @property
    def status(self) -> str | None: ...
    @property
    def created(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def replies(self) -> tuple[CommentReply, ...]: ...


@_final
class Presentation:
    def __new__(cls, path: _Path | None = None) -> Presentation: ...
    def save(self, path: _Path) -> None: ...
    def to_bytes(self) -> bytes: ...
    def to_pdf(self) -> bytes: ...
    def render_slide_to_png(self, slide_index: int, dpi: float = 150.0) -> bytes | None: ...
    def render_all_slides(self, dpi: float = 150.0) -> list[bytes]: ...
    def to_notes_pdf(self) -> bytes: ...
    def render_all_notes(self, dpi: float = 150.0) -> list[bytes]: ...
    @property
    def slide_width(self) -> _Length | None: ...
    @slide_width.setter
    def slide_width(self, value: int) -> None: ...
    @property
    def slide_height(self) -> _Length | None: ...
    @slide_height.setter
    def slide_height(self, value: int) -> None: ...
    @property
    def comment_authors(self) -> tuple[CommentAuthor, ...]: ...
    def add_comment_author(
        self,
        *,
        id: str,
        name: str,
        user_id: str,
        provider_id: str,
        initials: str | None = None,
    ) -> None: ...
    @property
    def slide_layouts(self) -> SlideLayoutCollection: ...
    @property
    def slides(self) -> SlideCollection: ...


@_final
class SlideLayout:
    def __new__(cls, *, _private: _Never) -> SlideLayout: ...
    @property
    def name(self) -> str | None: ...
    def __eq__(self, other: object, /) -> bool: ...


@_final
class SlideLayoutCollection:
    def __new__(cls, *, _private: _Never) -> SlideLayoutCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> SlideLayout: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[SlideLayout]: ...
    def __iter__(self) -> _Iterator[SlideLayout]: ...
    def index(self, slide_layout: SlideLayout) -> int: ...


@_final
class Slide:
    def __new__(cls, *, _private: _Never) -> Slide: ...
    @property
    def shapes(self) -> ShapeCollection: ...
    @property
    def placeholders(self) -> PlaceholderCollection: ...
    @property
    def notes_text(self) -> str | None: ...
    @notes_text.setter
    def notes_text(self, value: str) -> None: ...
    @property
    def slide_layout(self) -> SlideLayout: ...
    @property
    def hidden(self) -> bool: ...
    @hidden.setter
    def hidden(self, value: bool) -> None: ...
    @property
    def background(self) -> Background: ...
    @property
    def follow_master_background(self) -> bool: ...
    @follow_master_background.setter
    def follow_master_background(self, value: bool) -> None: ...
    @property
    def comments(self) -> tuple[Comment, ...]: ...
    def add_comment(
        self, *, id: str, author_id: str, created: str, text: str
    ) -> None: ...
    def reply_to_comment(
        self,
        comment_id: str,
        *,
        id: str,
        author_id: str,
        created: str,
        text: str,
    ) -> None: ...
    def move_comment(self, from_: int, to: int) -> None: ...
    def move_reply(self, comment_id: str, from_: int, to: int) -> None: ...


@_final
class SlideCollection:
    def __new__(cls, *, _private: _Never) -> SlideCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Slide: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Slide]: ...
    def __iter__(self) -> _Iterator[Slide]: ...
    def add_slide(self, layout: SlideLayout) -> Slide: ...
    def remove(self, slide: Slide) -> None: ...
    def move(self, from_: int, to: int) -> None: ...


@_final
class Background:
    def __new__(cls, *, _private: _Never) -> Background: ...
    @property
    def fill(self) -> FillFormat: ...


@_final
class Shape:
    def __new__(cls, *, _private: _Never) -> Shape: ...
    @property
    def left(self) -> _Length | None: ...
    @left.setter
    def left(self, value: int) -> None: ...
    @property
    def top(self) -> _Length | None: ...
    @top.setter
    def top(self, value: int) -> None: ...
    @property
    def width(self) -> _Length | None: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def height(self) -> _Length | None: ...
    @height.setter
    def height(self, value: int) -> None: ...
    @property
    def shape_id(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def rotation(self) -> float: ...
    @rotation.setter
    def rotation(self, value: float) -> None: ...
    @property
    def shape_type(self) -> _MSO_SHAPE_TYPE | None: ...
    @property
    def adjustments(self) -> AdjustmentCollection: ...
    @property
    def fill(self) -> FillFormat: ...
    @property
    def line(self) -> LineFormat: ...
    @property
    def xml(self) -> bytes: ...
    @property
    def image(self) -> Image: ...
    def replace_image(self, image_file: _ImageFile) -> None: ...
    @property
    def shapes(self) -> ShapeCollection: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def has_text_frame(self) -> bool: ...
    @property
    def text_frame(self) -> TextFrame: ...
    @property
    def has_table(self) -> bool: ...
    @property
    def table(self) -> Table: ...


@_final
class ShapeCollection:
    def __new__(cls, *, _private: _Never) -> ShapeCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Shape: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Shape]: ...
    def __iter__(self) -> _Iterator[Shape]: ...
    @property
    def title(self) -> Shape | None: ...
    @property
    def placeholders(self) -> PlaceholderCollection: ...
    def add_textbox(self, left: int, top: int, width: int, height: int) -> Shape: ...
    def add_shape(
        self, shape_type: _MSO_SHAPE | str, left: int, top: int, width: int, height: int
    ) -> Shape: ...
    def add_connector(
        self,
        connector_type: _MSO_CONNECTOR_TYPE,
        begin_x: int,
        begin_y: int,
        end_x: int,
        end_y: int,
    ) -> Shape: ...
    def add_group_shape(self) -> Shape: ...
    def add_table(
        self, rows: int, cols: int, left: int, top: int, width: int, height: int
    ) -> Shape: ...
    def add_picture(
        self,
        image_file: _ImageFile,
        left: int,
        top: int,
        width: int | None = None,
        height: int | None = None,
    ) -> Shape: ...
    def remove(self, shape: Shape) -> None: ...


@_final
class PlaceholderCollection:
    def __new__(cls, *, _private: _Never) -> PlaceholderCollection: ...
    def __getitem__(self, placeholder_idx: int, /) -> Shape: ...


@_final
class Image:
    def __new__(cls, *, _private: _Never) -> Image: ...
    @property
    def blob(self) -> bytes: ...
    @property
    def content_type(self) -> str: ...
    @property
    def ext(self) -> str: ...


@_final
class AdjustmentCollection:
    def __new__(cls, *, _private: _Never) -> AdjustmentCollection: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int, /) -> float: ...
    def __setitem__(self, index: int, value: float, /) -> None: ...
    def __iter__(self) -> _Iterator[float]: ...


@_final
class FillFormat:
    def __new__(cls, *, _private: _Never) -> FillFormat: ...
    @property
    def type(self) -> _MSO_FILL_TYPE | None: ...
    def solid(self) -> None: ...
    def background(self) -> None: ...
    @property
    def fore_color(self) -> ColorFormat: ...


@_final
class LineFormat:
    def __new__(cls, *, _private: _Never) -> LineFormat: ...
    @property
    def color(self) -> ColorFormat: ...
    @property
    def fill(self) -> FillFormat: ...
    @property
    def width(self) -> _Length: ...
    @width.setter
    def width(self, value: int | None) -> None: ...


@_final
class ColorFormat:
    def __new__(cls, *, _private: _Never) -> ColorFormat: ...
    @property
    def rgb(self) -> _RGBColor | None: ...
    @rgb.setter
    def rgb(self, value: _RGBColor) -> None: ...


@_final
class TextFrame:
    def __new__(cls, *, _private: _Never) -> TextFrame: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def paragraphs(self) -> ParagraphCollection: ...
    def add_paragraph(self) -> Paragraph: ...
    @property
    def autofit(self) -> str | None: ...


@_final
class Paragraph:
    def __new__(cls, *, _private: _Never) -> Paragraph: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def level(self) -> int: ...
    @level.setter
    def level(self, value: int) -> None: ...
    @property
    def font(self) -> Font: ...
    @property
    def runs(self) -> RunCollection: ...


@_final
class ParagraphCollection:
    def __new__(cls, *, _private: _Never) -> ParagraphCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Paragraph: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Paragraph]: ...
    def __iter__(self) -> _Iterator[Paragraph]: ...


@_final
class Run:
    def __new__(cls, *, _private: _Never) -> Run: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def font(self) -> Font: ...


@_final
class RunCollection:
    def __new__(cls, *, _private: _Never) -> RunCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Run: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Run]: ...
    def __iter__(self) -> _Iterator[Run]: ...


@_final
class Font:
    def __new__(cls, *, _private: _Never) -> Font: ...
    @property
    def name(self) -> str | None: ...
    @property
    def color(self) -> str | None: ...
    @property
    def bold(self) -> bool | None: ...
    @bold.setter
    def bold(self, value: bool | None) -> None: ...
    @property
    def size(self) -> _Length | None: ...
    @size.setter
    def size(self, value: int | None) -> None: ...


@_final
class Table:
    def __new__(cls, *, _private: _Never) -> Table: ...
    @property
    def columns(self) -> ColumnCollection: ...
    def cell(self, row: int, col: int) -> Cell: ...


@_final
class ColumnCollection:
    def __new__(cls, *, _private: _Never) -> ColumnCollection: ...
    def __len__(self) -> int: ...
    @_overload
    def __getitem__(self, key: int, /) -> Column: ...
    @_overload
    def __getitem__(self, key: slice, /) -> list[Column]: ...
    def __iter__(self) -> _Iterator[Column]: ...


@_final
class Column:
    def __new__(cls, *, _private: _Never) -> Column: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...


@_final
class Cell:
    def __new__(cls, *, _private: _Never) -> Cell: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
