[build-system]
requires = ["maturin>=1.9,<2"]
build-backend = "maturin"

[project]
name = "rpptx"
version = "0.13.0"
requires-python = ">=3.9"
description = "Python bindings for rpptx"
license = "MIT OR Apache-2.0"

[tool.maturin]
python-source = "python"
module-name = "rpptx._rpptx"
features = ["extension-module"]
