[package]
name = "oxml-drawing"
description = "DrawingML models and serialization for OOXML documents"
readme = "README.md"
version = "0.11.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish = true

[package.metadata.release]
shared-version = "incubating"
tag-name = "rpptx-v{{version}}"

[dependencies]
oxml-core.workspace = true
quick-xml.workspace = true

[dev-dependencies]
oxml-opc.workspace = true
